server:
  port: 8080
  servlet:
    session:
      timeout: 4h
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/postgres
      username: comodiary
      password: comodataconnect
      driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
