server:
  port: 8181
  servlet:
    session:
      timeout: 4h
spring:
  datasource:
    url: jdbc:h2:file:./data/mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #    url: jdbc:postgresql://localhost:5432/postgres
  #    username: sa
  #    password:
  #    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
